export const RAZAS_PERROS = [
  "Akita",
  "Alaskan Malamute",
  "American Staffordshire Terrier",
  "Australian Shepherd",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Bloodhound",
  "Border Collie",
  "Borzoi",
  "Boston Terrier",
  "Boxer",
  "Bretón Español",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Bullmastiff",
  "Cane Corso",
  "Caniche",
  "Cavalier King Charles",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel",
  "Collie",
  "Coton de Tulear",
  "Dachshund (Salchicha)",
  "Dalmatian",
  "Dóberman Pinscher",
  "Dogue de Bordeaux",
  "English Springer Spaniel",
  "Estaffordshire Bull Terrier",
  "Fila Brasileño",
  "Fox Terrier",
  "Galgo Español",
  "German Pinscher",
  "German Shepherd (Ovejero Alemán)",
  "German Shorthaired Pointer",
  "Golden Retriever",
  "Gordon Setter",
  "Gran Danés",
  "Gran Pirineo",
  "Greyhound",
  "Havanese",
  "Hokkaido",
  "Husky Siberiano",
  "Ibizan Hound",
  "Irish Setter",
  "Irish Terrier",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Komondor",
  "Labrador Retriever",
  "Lakeland Terrier",
  "Lhasa Apso",
  "Maltés",
  "Mastín Español",
  "Mastín Napolitano",
  "Mestizo",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Mudi",
  "Newfoundland",
  "Norfolk Terrier",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Otra",
  "Ovejero Alemán",
  "Papillon",
  "Parson Russell Terrier",
  "Patterdale Terrier",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Perro de Agua Español",
  "Perro de Presa Canario",
  "Pharaoh Hound",
  "Pitbull",
  "Pointer",
  "Pomeranian",
  "Poodle",
  "Portuguese Water Dog",
  "Pug",
  "Pumi",
  "Pyrenean Mastiff",
  "Pyrenean Sheepdog",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Rough Collie",
  "Russian Black Terrier",
  "Russian Toy",
  "Saluki",
  "Samoyed",
  "Schnauzer",
  "Schnauzer Gigante",
  "Schnauzer Miniatura",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Sennenhund",
  "Shar Pei",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Silken Windhound",
  "Silky Terrier",
  "Smooth Collie",
  "Smooth Fox Terrier",
  "Soft Coated Wheaten Terrier",
  "Spanish Mastiff",
  "Spanish Water Dog",
  "Spinone Italiano",
  "Staffordshire Bull Terrier",
  "Standard Schnauzer",
  "Stichelhaar",
  "Sussex Spaniel",
  "Swedish Lapphund",
  "Swedish Vallhund",
  "Swiss Mountain Dog",
  "Thai Ridgeback",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Toy Fox Terrier",
  "Toy Poodle",
  "Toy Terrier",
  "Turkish Kangal",
  "Weimaraner",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Wheaten Terrier",
  "Whippet",
  "White Swiss Shepherd",
  "Wire Fox Terrier",
  "Wirehaired Dachshund",
  "Wirehaired Pointing Griffon",
  "Xoloitzcuintli",
  "Yakutian Laika",
  "Yorkshire Terrier",
  "Dogo Argentino",
]

export const RAZAS_GATOS = [
  "Abisinio",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Angora",
  "Angora Turco",
  "Asian",
  "Azul Ruso",
  "Balinés",
  "Bengalí",
  "Birman",
  "Bobtail Japonés",
  "Bombay",
  "Brasil Shorthair",
  "British Longhair",
  "British Shorthair",
  "Burmés",
  "Burmilla",
  "Cartujo",
  "Chartreux",
  "Colorpoint",
  "Cornish Rex",
  "Criollo",
  "Cymric",
  "Devon Rex",
  "Donskoy",
  "Ebony",
  "Egipcio Mau",
  "Europeo",
  "Europeo de Pelo Corto",
  "Europeo de Pelo Largo",
  "Exotic Shorthair",
  "Exótico",
  "Gato Ruso",
  "German Rex",
  "Gris Ruso",
  "Havana Brown",
  "Highlander",
  "Himalayo",
  "Javanés",
  "Khao Manee",
  "Korat",
  "Korean Bobtail",
  "LaPerm",
  "Longhair",
  "Lynx",
  "Maine Coon",
  "Mandalay",
  "Manx",
  "Mau Egipcio",
  "Mestizo",
  "Minskin",
  "Munchkin",
  "Nebelung",
  "Neva Masquerade",
  "Noruego del Bosque",
  "Ocicat",
  "Ojos Azules",
  "Otra",
  "Persa",
  "Persa de Pelo Largo",
  "Peterbald",
  "Pixiebob",
  "Ragamuffin",
  "Ragdoll",
  "Red Selkirk",
  "Ruso Azul",
  "Ruso Blanco",
  "Ruso Negro",
  "Sacred Birman",
  "Savannah",
  "Scottish Fold",
  "Scottish Shorthair",
  "Selkirk Rex",
  "Siberiano",
  "Siamés",
  "Siamés Moderno",
  "Siamés Tradicional",
  "Singapurés",
  "Snowshoe",
  "Sokoke",
  "Somali",
  "Sphynx",
  "Suphalak",
  "Tailandés",
  "Tiffani",
  "Tiffany",
  "Tonkinés",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
]

export const obtenerRazas = (tipoAnimal: "Perro" | "Gato"): string[] => {
  const razas = tipoAnimal === "Perro" ? RAZAS_PERROS : RAZAS_GATOS
  // Eliminar duplicados usando Set y normalizar
  const razasUnicas = Array.from(new Set(razas))
  return razasUnicas.sort((a, b) => a.localeCompare(b, "es", { sensitivity: "base" }))
}
